

---
- name: First Playbook
  hosts: all
  tasks:
  - name: Add docker deb repository 
    shell: "echo \"deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable\""
    register: repository_val

  - name: Add docker deb repository file
    ansible.builtin.copy:
      dest: "/tmp/ansible.test"
      content: "{{ repository_val.stdout }}"