- name: Install Docker on Debian
  import_tasks: debian.yml
  when: ansible_facts['os_family']|lower == 'debian'

- name: Install Docker on CentOs or Redhat linux
  import_tasks: centos.yml
  when: ansible_facts['os_family']|lower == 'redhat'