- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ podman_home_directory }}"
    - "{{ path.nginx.home }}"
    - "{{ path.nginx.home }}/conf"
    - "{{ path.nginx.home }}/conf/vhosts"

- name: Copy Nginx Host Configuration file
  template:
    src: "vhosts.conf.j2"
    dest: "{{ path.nginx.home }}/conf/vhosts/{{ item.name }}.conf"
    mode: 0644
  loop: "{{ servers_to_connect }}"

- name: nginx live reload
  command: "{{ item }}"
  with_items:
    - "podman kill --signal HUP nginx"