- name: Install docker python package
  pip:
    name: docker

- name: Pull an image
  containers.podman.podman_image:
    name: linuxserver/wireguard

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: "/data/wireguard/config"
    state: directory
    mode: '0755'

- name: enable wireguard module
  command: 'modprobe wireguard'
  become: true

- name: enable iptables module
  command: 'modprobe ip_tables'
  become: true

- name: Create a wireguard container
  containers.podman.podman_container:
    name: wireguard
    image: linuxserver/wireguard
    ports:
      - "51820:51820/udp"
    env:
      PUID: "ansible_facts['user_uid']"
      PGID: "ansible_facts['user_gid']"
      TZ: Europe/London
      SERVERURL: "{{ ansible_host }}"
      SERVERPORT: "51820"
      PEERS: "1"
      PEERDNS: "auto"
      INTERNAL_SUBNET: "10.13.13.0"
      ALLOWEDIPS: 0.0.0.0/0
      LOG_CONFS: "true"
    volume:
      - "/data/wireguard/config:/config"
      - "/lib/modules:/lib/modules"
    capabilities : 
      - "NET_ADMIN"
      - "SYS_MODULE"
    sysctl:
      net.ipv4.conf.all.src_valid_mark: 1
      net.ipv4.ip_forward: 1
    restart_policy: unless-stopped
