- name: Install docker python package
  pip:
    name: docker

- name: Pull an image
  community.docker.docker_image:
    name: postgres:12
    source: pull

- name: Pull an image
  community.docker.docker_image:
    name: sonarqube:community
    source: pull

- name: Create a volume
  community.docker.docker_volume:
    name: sonarqube_data

- name: Create a volume
  community.docker.docker_volume:
    name: sonarqube_logs

- name: Create a volume
  community.docker.docker_volume:
    name: postgresql

- name: Create a volume
  community.docker.docker_volume:
    name: postgresql_data

- name: Create a network
  community.docker.docker_network:
    name: "sonar_network"

- name: Create a postgres container
  community.docker.docker_container:
    name: postgres
    image: postgres:12
    networks:
      - name: "sonar_network"
    env:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes: 
      - "postgresql:/var/lib/postgresql"
      - "postgresql_data:/var/lib/postgresql/data"
    restart_policy: unless-stopped

- name: vm setting
  shell: "sysctl -w vm.max_map_count=262144"

- name: Create a sonarqube container
  community.docker.docker_container:
    name: sonarqube
    image: sonarqube:community
    networks:
      - name: "sonar_network"
    ports:
      - "30007:9000"
    env:
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes: 
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
    restart_policy: unless-stopped
