- name: Include all /vars/*.yml files
  ansible.builtin.include_vars:
    dir: vars
    extensions:
      - 'yml'


- name: Install nginx on CentOs or Redhat linux
  import_tasks: centos.yml
  when: ansible_facts['os_family']|lower == 'redhat'